### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by appelsson** [smoothgesturesplus/Issues#38] opened 2016-01-20 07:48 UTC
I have the latest Smooth Gestures (2.0) from the store.
Today I get a popup everytime when I try to draw a gesture:

smooth gestures PLUS needs to be Updated
To update smooth gestures PLUS:
Open the Extensions Page
Checkmark "Developer Mode"
Click "Update Extensions Now"

But this is the latest release. 
Removed, reinstalled the extension, but problem still exists and it's not working now.

**Comment by bbleeker** [comment] 2016-01-20 08:01
I have the same problem.

**Comment by MeszesKPT** [comment] 2016-01-20 08:06
Same issue here, can't use the extension this way.

**Comment by want2die** [comment] 2016-01-20 08:06
update and not working. same problem. please fix this

**Comment by guasek** [comment] 2016-01-20 11:19
:+1:

**Comment by klip** [comment] 2016-01-20 12:03
Same for me

**Comment by want2die** [comment] 2016-01-21 11:52
the issue is resolved by itself

**Closed** 2016-01-21 17:07 UTC
